name: Generate Traffic

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tor and Wget
        run: |
          sudo apt-get update
          sudo apt-get install -y tor wget

      - name: Read URLs from file
        run: |
          cat urls.txt
          echo "::set-env name=URLS::$(cat urls.txt)"

      - name: Generate traffic
        env:
          HOST: ${{ secrets.HOST }}
          URLS: ${{ env.URLS }}
        run: |
          user_agents=(
            "Mozilla/5.0 (Android 12; Mobile; LG-M255; rv:100.0) Gecko/100.0 Firefox/100.0Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36"
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
          )

          urls=($URLS)

          sleep_duration=5

          while true; do
            N=$((RANDOM % 100 + 1))
            echo "Making ${N} random requests"

            for ((i=1; i<=N; i++)); do
              random_url=${urls[$RANDOM % ${#urls[@]}]}
              random_user_agent=${user_agents[$RANDOM % ${#user_agents[@]}]}

              (
                torsocks curl -A "${random_user_agent}" "${random_url}" -o /dev/null
              ) &
            done

            wait

            sleep "${sleep_duration}"
          done
