
name: gen-traffic

on:
  schedule:
    - cron: "*/10 * * * *" # ทำงานทุก 10 นาที
jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tor and Wget
        run: |
          sudo apt-get update
          sudo apt-get install -y tor wget

      - name: Generate traffic
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          while true; do
            N=$(shuf -i 1-100 -n 1)
            echo "Making ${N} random requests"
            shuf -n ${N} urls.txt | envsubst | xargs -t -I {} bash -c "curl -A 'Mozilla/5.0 (Android 12; Mobile; LG-M255; rv:100.0) Gecko/100.0 Firefox/100.0Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36' {} -o /dev/null; sleep 1;" || true &
            sleep 5
          done
